on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          to_whatsapp_no: ${{ secrets.to_whatsapp_no }}


        uses: KhaledAhmed-Ibtikar/whatsapp-push-notify-action@1.3
        
      - name : Push notification on Whatsapp with custom messages
        run: |
          echo 'Start!'
